export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const GET_ERRORS = 'GET_ERRORS';
export const CLEAR_ERRORS = 'CLEAR_ERRORS';
export const GET_SUCCESS = 'GET_SUCCESS';
export const CLEAR_SUCCESS = 'CLEAR_SUCCESS';
export const GET_PROFILE = 'GET_PROFILE';
export const GET_CURRENT_COURSES = 'GET_CURRENT_COURSES';
export const GET_EXERCISE_LIST = 'GET_EXERCISE_LIST';
export const GET_USERS = 'GET_USERS';

